-- ============================================================
-- SignCi — Tables pour les ANNO NCES (Supabase / PostgreSQL)
-- À exécuter dans l'éditeur SQL de Supabase (Dashboard → SQL Editor).
--
-- L'application Flutter lit/écrit ces tables directement via
-- lib/services/supabase_service.dart (colonnes en camelCase,
-- sauf created_at en snake_case pour les commentaires).
-- ============================================================

-- Annonces publiées par l'administration.
create table if not exists public.annonces (
  id bigint generated by default as identity primary key,
  titre text not null,
  description text,
  image text,
  auteur text default 'Administration SignCi',
  "datePublication" timestamptz default now(),
  likes int default 0
);

-- Commentaires citoyens sur les annonces.
create table if not exists public.annonce_comments (
  id bigint generated by default as identity primary key,
  "annonceId" bigint not null references public.annonces(id) on delete cascade,
  pseudo text default 'Citoyen SignCi',
  contenu text not null,
  created_at timestamptz default now()
);

-- Pour un déploiement de démonstration, on laisse la lecture/écriture ouverte.
-- (En production, créez des policies RLS en fonction des rôles.)
alter table public.annonces enable row level security;
alter table public.annonce_comments enable row level security;

create policy "lecture annonces" on public.annonces
  for select using (true);
create policy "ecriture annonces" on public.annonces
  for insert with check (true);
create policy "modification annonces" on public.annonces
  for update using (true);
create policy "suppression annonces" on public.annonces
  for delete using (true);

create policy "lecture commentaires" on public.annonce_comments
  for select using (true);
create policy "ecriture commentaires" on public.annonce_comments
  for insert with check (true);

-- ============================================================
-- STORAGE — Bucket des PHOTOS (signalements & annonces)
-- L'app upload les photos ici et stocke l'URL publique dans
-- la colonne `image`. Le bucket doit être public.
-- ============================================================
insert into storage.buckets (id, name, public)
values ('signalements', 'signalements', true)
on conflict (id) do nothing;

-- Autorise le public (clé anon) à lire les photos...
drop policy if exists "public_select_signalement_photos" on storage.objects;
create policy "public_select_signalement_photos" on storage.objects
  for select to public using (bucket_id = 'signalements');

-- ...et à en ajouter de nouvelles.
drop policy if exists "public_insert_signalement_photos" on storage.objects;
create policy "public_insert_signalement_photos" on storage.objects
  for insert to public with check (bucket_id = 'signalements');